# 11-3 Playing with dataframes
Adapted from Pandas "Getting startd" guide at https://pandas.pydata.org/docs/getting_started/intro_tutorials/06_calculate_statistics.html

In [4]:
import pandas as pd
titanic = pd.read_csv("titanic.csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
print('average passenger age: ', titanic.Age.mean())
print('average male passenger age: ', titanic[titanic.Sex == 'male'].Age.mean())
print('average female passenger age: ', titanic[titanic.Sex == 'female'].Age.mean())

average passenger age:  29.69911764705882
average male passenger age:  30.72664459161148
average female passenger age:  27.915708812260537

In [21]:
# Another way to do this:
# 1. select the Age and Sex columns:
#.  titanic[["Sex", "Age"]]
# 2. split into groups based on "Sex": 
# titanic[["Sex", "Age"]].groupby("Sex")
# 3. get the mean of each group
titanic[["Sex", "Age"]].groupby("Sex").mean()

              Age
Sex
female  27.915709
male    30.726645

In [25]:
# Average age of survivors vs casualties:
titanic[["Survived", "Age"]].groupby("Survived").mean()

                Age
Survived
0         30.626179
1         28.343690

In [26]:
# describe method prints some statistical info:
titanic[titanic.Survived == 1].describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,342.000000,342.0,342.000000,290.000000,342.000000,342.000000,342.000000
mean,444.368421,1.0,1.950292,28.343690,0.473684,0.464912,48.395408
std,252.358840,0.0,0.863321,14.950952,0.708688,0.771712,66.596998
min,2.000000,1.0,1.000000,0.420000,0.000000,0.000000,0.000000
25%,250.750000,1.0,1.000000,19.000000,0.000000,0.000000,12.475000
50%,439.500000,1.0,2.000000,28.000000,0.000000,0.000000,26.000000
75%,651.500000,1.0,3.000000,36.000000,1.000000,1.000000,57.000000
max,890.000000,1.0,3.000000,80.000000,4.000000,5.000000,512.329200

In [30]:
titanic[["Survived", "Age"]].groupby("Survived").describe()

            Age
          count       mean        std   min   25%   50%   75%   max
Survived
0         424.0  30.626179  14.172110  1.00  21.0  28.0  39.0  74.0
1         290.0  28.343690  14.950952  0.42  19.0  28.0  36.0  80.0

In [32]:
titanic.groupby("Sex").mean(numeric_only=True)

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
Sex,,,,,,,
female,431.028662,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818
male,454.147314,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893