# 11-4 Oil prices data from statcan

In [37]:
import pandas as pd

gp = pd.read_csv("1810000101_databaseLoadingData.csv", skipinitialspace=True)
gp

,REF_DATE,GEO,DGUID,Type of fuel,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016-01,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,92.6,NaN,NaN,NaN,1
1,2016-02,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,86.7,NaN,NaN,NaN,1
2,2016-03,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,91.9,NaN,NaN,NaN,1
3,2016-04,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,100.0,NaN,NaN,NaN,1
4,2016-05,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,104.1,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2313,2025-10,"Yellowknife, Northwest Territories",2011A00056106023,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v735091,19.2,145.0,NaN,NaN,NaN,1
2314,2025-11,"Yellowknife, Northwest Territories",2011A00056106023,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v735091,19.2,144.3,NaN,NaN,NaN,1
2315,2025-12,"Yellowknife, Northwest Territories",2011A00056106023,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v735091,19.2,139.3,NaN,NaN,NaN,1
2316,2026-01,"Yellowknife, Northwest Territories",2011A00056106023,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v735091,19.2,133.9,NaN,NaN,NaN,1
2317,2026-02,"Yellowknife, Northwest Territories",2011A00056106023,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v735091,19.2,133.4,NaN,NaN,NaN,1

In [27]:
gpGTA = gp[gp['GEO'] == 'Toronto, Ontario']
gpGTA['REF_DATE']

976     2016-01
977     2016-02
978     2016-03
979     2016-04
980     2016-05
         ...
1093    2025-10
1094    2025-11
1095    2025-12
1096    2026-01
1097    2026-02
Name: REF_DATE, Length: 122, dtype: object

In [12]:
places

array(['Canada', "St. John's, Newfoundland and Labrador",
       'Charlottetown and Summerside, Prince Edward Island',
       'Halifax, Nova Scotia', 'Saint John, New Brunswick',
       'Québec, Quebec', 'Montréal, Quebec',
       'Ottawa-Gatineau, Ontario part, Ontario/Quebec',
       'Toronto, Ontario', 'Thunder Bay, Ontario', 'Winnipeg, Manitoba',
       'Regina, Saskatchewan', 'Saskatoon, Saskatchewan',
       'Edmonton, Alberta', 'Calgary, Alberta',
       'Vancouver, British Columbia', 'Victoria, British Columbia',
       'Whitehorse, Yukon', 'Yellowknife, Northwest Territories'],
      dtype=object)

In [31]:
gp[gp.GEO == 'Canada']

,REF_DATE,GEO,DGUID,Type of fuel,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2016-01,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,92.6,NaN,NaN,NaN,1
1,2016-02,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,86.7,NaN,NaN,NaN,1
2,2016-03,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,91.9,NaN,NaN,NaN,1
3,2016-04,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,100.0,NaN,NaN,NaN,1
4,2016-05,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,104.1,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2025-10,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,137.2,NaN,NaN,NaN,1
118,2025-11,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,139.6,NaN,NaN,NaN,1
119,2025-12,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,129.6,NaN,NaN,NaN,1
120,2026-01,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,130.4,NaN,NaN,NaN,1
121,2026-02,Canada,2016A000011124,Regular unleaded gasoline at self service fill...,Cents per litre,57,units,0,v1352087861,20.2,134.9,NaN,NaN,NaN,1