In [1]:
import numpy as np
import pandas as pd

# Monday March 16th 2026

## Introduction to Pandas

![Panda Picture](panda.jpg)

- We have seen how Numpy arrays are great tools for working with data of a uniform type.
    - In Pythonic words, we say Numpy arrays are homogeneous containers.
    - This allows Numpy arrays to have a single type - called their dtype.

In [2]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1.,2.,3.],[4.,5,6]])
print(f"A = {A}")
print(f"B = {B}")

A = [[1 2 3]
 [4 5 6]]
B = [[1. 2. 3.]
 [4. 5. 6.]]

In [3]:
print(f"A has dtype : {A.dtype}")
print(f"B has dtype : {B.dtype}")

A has dtype : int64
B has dtype : float64

Having a homogeneous type has many advantages (there are three key ones lets try to name them here!)

-
-
-

However, we are oftentimes faced with data that is not homogeneous. In these cases, it would be nice to have a library with some of the similar functionality as Numpy i.e. **vectorization** and **columnization**, without the constraint of homogeneity. 

Such a library is **Pandas**.

### Pandas

Just as Numpy offers us the new data type of Numpy nd-arrays, Pandas comes with two new data types called **series** and **data frames**.

### Series

A **series** is a one-dimensional labeled array.

In [ ]:
a = [1, 7, 2]
ser1 = pd.Series(data = a)

print(ser1)

0    1
1    7
2    2
dtype: int64

In [7]:
print(ser1[2])

2

In [9]:
ser2 = pd.Series(data = a, index = ["x", "y", "z"])
print(ser2)

x    1
y    7
z    2
dtype: int64

In [5]:
d = {"a" : 1, "b" : 2, "c" : 3}
ser = pd.Series(data = d, index = ["a","b","c"])
print(ser)

a    1
b    2
c    3
dtype: int64

### DataFrames

A **DataFrame** is a two-dimensional labeled data structure that consists of columns and rows. A DataFrame represents a spreadsheet-like data structure where each column is a **Series**.

In [11]:
data = {
    "Name" : ["John", "Nathan", "Lily", "Corrin"],
    "Age" : [26,27,19,26],
    "City" : ["Hamilton", "Dundas", "Halifax", "Charlottetown"]
}

df = pd.DataFrame(data)

df

     Name  Age           City
0    John   26       Hamilton
1  Nathan   27         Dundas
2    Lily   19        Halifax
3  Corrin   26  Charlottetown

In [22]:
data = [
    ["John", 26, "Hamilton"],
    ['Nathan', 27, "Dundas"],
    ["Lily", 19, "Halifax"],
    ["Corrin", 26, "Charlottetown"]
]

unique_id = [400130523, 400127887, 40130877, 555555555]

cols = ["Name", "Age", "City"]

df = pd.DataFrame(data, columns = cols, index = unique_id)

df

             Name  Age           City
400130523    John   26       Hamilton
400127887  Nathan   27         Dundas
40130877     Lily   19        Halifax
555555555  Corrin   26  Charlottetown

In [29]:
df["Name"]

400130523      John
400127887    Nathan
40130877       Lily
555555555    Corrin
Name: Name, dtype: object

In [30]:
df["City"]

400130523         Hamilton
400127887           Dundas
40130877           Halifax
555555555    Charlottetown
Name: City, dtype: object

What if we want to see a row instead of a column?

Here we can use the `loc` method!

In [31]:
df.loc[400130523]

Name        John
Age           26
City    Hamilton
Name: 400130523, dtype: object

In [32]:
df.loc[[400130523,555555555]]

             Name  Age           City
400130523    John   26       Hamilton
555555555  Corrin   26  Charlottetown

In [ ]:
df = pd.read_csv("grades.csv")

df

Index(['# First name', ' Last name', ' Student number', ' Quizzes average',
       ' HW1 mark', ' HW2 mark', ' HW3 mark', ' Exam1 mark', ' Exam2 mark',
       ' Final exam mark'],
      dtype='object')

In [45]:
df.columns

Index(['# First name', ' Last name', ' Student number', ' Quizzes average',
       ' HW1 mark', ' HW2 mark', ' HW3 mark', ' Exam1 mark', ' Exam2 mark',
       ' Final exam mark'],
      dtype='object')

In [54]:
df.loc[len(df)+1] = ["Mike", "Wazowski", 400130523, 29.9, 29.9, 29.9, 29.9, 22.2, 22.2, 30.2]

df.drop(index = 222222222)

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,BARRY,LAMB,620565656,96.0,77.0,82.0,91.0,88.0,78.0,91.0
1,NARIMAN,PELUCHONDELAGARZA,107856531,94.0,76.0,87.0,90.0,90.0,67.0,88.0
2,VITALY,KHAN,7943944,92.0,79.0,85.0,92.0,76.0,60.0,87.0
3,NATALYA,SUTRADHAR,114037001,90.0,75.0,78.0,88.0,90.0,67.0,84.0
4,MAGARET,HIRJI,581943811,88.0,76.0,91.0,98.0,96.0,56.0,81.0
...,...,...,...,...,...,...,...,...,...,...
254,Mike,Wazowski,400130523,29.9,29.9,29.9,29.9,22.2,22.2,30.2
255,Mike,Wazowski,400130523,29.9,29.9,29.9,29.9,22.2,22.2,30.2
256,Mike,Wazowski,400130523,29.9,29.9,29.9,29.9,22.2,22.2,30.2
257,Mike,Wazowski,400130523,29.9,29.9,29.9,29.9,22.2,22.2,30.2
258,Mike,Wazowski,400130523,29.9,29.9,29.9,29.9,22.2,22.2,30.2

In [58]:
df.drop(index = [254,255,256,257,258,253,222222222])

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,BARRY,LAMB,620565656,96.0,77.0,82.0,91.0,88.0,78.0,91.0
1,NARIMAN,PELUCHONDELAGARZA,107856531,94.0,76.0,87.0,90.0,90.0,67.0,88.0
2,VITALY,KHAN,7943944,92.0,79.0,85.0,92.0,76.0,60.0,87.0
3,NATALYA,SUTRADHAR,114037001,90.0,75.0,78.0,88.0,90.0,67.0,84.0
4,MAGARET,HIRJI,581943811,88.0,76.0,91.0,98.0,96.0,56.0,81.0
...,...,...,...,...,...,...,...,...,...,...
246,JANAYA,ELZOEIBY,248015969,94.0,72.0,82.0,91.0,92.0,69.0,93.0
247,PATRYK,BERNIQUER,970187185,95.0,72.0,88.0,94.0,88.0,67.0,95.0
248,ARIANNA,DMITROVICH,300391145,91.0,73.0,84.0,94.0,96.0,75.0,83.0
249,CHERISE,MILEUSNIC,149614639,92.0,78.0,79.0,91.0,90.0,65.0,90.0
250,DUMITRU,SHAH,849296811,94.0,65.0,86.0,87.0,83.0,74.0,85.0

In [61]:
df.describe()

df[df[' Final exam mark']> 92.0]

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
5,RAINA,SUTRADHAR,367541502,90.0,70.0,84.0,91.0,91.0,59.0,95.0
21,GREGOR,GOPAULROLDAN,75524279,89.0,83.0,80.0,93.0,94.0,63.0,95.0
24,MARITZA,YIN,128992445,93.0,82.0,98.0,87.0,90.0,64.0,97.0
39,MARITA,HUANG,217623542,81.0,79.0,81.0,92.0,81.0,72.0,94.0
57,TAWNYA,KHURANA,187126246,100.0,69.0,91.0,92.0,87.0,64.0,93.0
67,AHMET,VEERMAN,485438097,93.0,68.0,84.0,83.0,87.0,71.0,93.0
74,FORBES,MILEUSNIC,91063682,89.0,77.0,82.0,92.0,78.0,69.0,95.0
86,SATWINDER,ISLAM,679421923,97.0,67.0,84.0,83.0,84.0,66.0,93.0
91,MARY-LOU,OLUTAYO,119625290,98.0,67.0,83.0,88.0,82.0,63.0,100.0
118,ORLANDO,KHAN,485689330,98.0,73.0,87.0,94.0,79.0,72.0,93.0
129,DONNA,SHARMA,185017481,100.0,85.0,84.0,90.0,90.0,59.0,99.0
154,YAM,BAYAN,8912621,96.0,77.0,82.0,88.0,95.0,72.0,93.0
159,CELESTINE,AZOM,454169056,91.0,62.0,79.0,93.0,81.0,70.0,95.0
166,VIRGINA,ANGEL,832591342,86.0,80.0,86.0,87.0,85.0,63.0,93.0
171,KOLTEN,MACDONALD,983697220,90.0,73.0,84.0,86.0,88.0,69.0,94.0
186,ANHAD,WILFRED,731558064,89.0,81.0,80.0,82.0,97.0,67.0,94.0
188,YUYING,DEHMESHKI,285211298,95.0,77.0,74.0,93.0,89.0,65.0,94.0
202,MICHAL,PRESTI,714449327,100.0,76.0,81.0,90.0,94.0,67.0,96.0
212,NATACHA,HOOD,531062921,100.0,74.0,91.0,85.0,80.0,61.0,95.0
213,MARWA,MOHSIN,757587905,100.0,88.0,77.0,86.0,89.0,64.0,95.0
215,MADDIE,LIU,99421869,96.0,74.0,80.0,90.0,85.0,62.0,95.0
227,RIA,PRABAHARAN,209237590,93.0,79.0,82.0,88.0,87.0,62.0,96.0
234,ANTONINA,VECCHIO,226246762,90.0,76.0,93.0,93.0,83.0,62.0,93.0
246,JANAYA,ELZOEIBY,248015969,94.0,72.0,82.0,91.0,92.0,69.0,93.0
247,PATRYK,BERNIQUER,970187185,95.0,72.0,88.0,94.0,88.0,67.0,95.0

In [63]:
df.loc[0:5, " Quizzes average":]

,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,96.0,77.0,82.0,91.0,88.0,78.0,91.0
1,94.0,76.0,87.0,90.0,90.0,67.0,88.0
2,92.0,79.0,85.0,92.0,76.0,60.0,87.0
3,90.0,75.0,78.0,88.0,90.0,67.0,84.0
4,88.0,76.0,91.0,98.0,96.0,56.0,81.0
5,90.0,70.0,84.0,91.0,91.0,59.0,95.0

READ CSVs and Excel files!!!