In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Monday March 16th 2026

## Introduction to Pandas

![Panda Picture](panda.jpg)

- We have seen how Numpy arrays are great tools for working with data of a uniform type.
    - In Pythonic words, we say Numpy arrays are homogeneous containers.
    - This allows Numpy arrays to have a single type - called their dtype.

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1.,2.,3.],[4.,5,6]])
print(f"A = {A}")
print(f"B = {B}")

In [ ]:
print(f"A has dtype : {A.dtype}")
print(f"B has dtype : {B.dtype}")

Having a homogeneous type has many advantages (there are three key ones lets try to name them here!)

-
-
-

However, we are oftentimes faced with data that is not homogeneous. In these cases, it would be nice to have a library with some of the similar functionality as Numpy i.e. **vectorization** and **columnization**, without the constraint of homogeneity. 

Such a library is **Pandas**.

### Pandas

Just as Numpy offers us the new data type of Numpy nd-arrays, Pandas comes with two new data types called **series** and **data frames**.

![Panda picture](KungFuPanda.png)

### Series

A **series** is a one-dimensional labeled array.

In [ ]:
a = [1, 7, 2]
ser1 = pd.Series(data = a)

print(ser1)

In [ ]:
print(ser1[2])

In [ ]:
ser2 = pd.Series(data = a, index = ["x", "y", "z"])
print(ser2)

In [ ]:
d = {"a" : 1, "b" : 2, "c" : 3}
ser = pd.Series(data = d, index = ["a","b","c"])
print(ser)

### Labels are helpful

In [ ]:
hw1_data = {'John' : 72.0, 'Nathan' : 100.0, 'Matthew' : 88.9}
hw2_data = {'Nathan' : 100.0, 'Matthew' : 93.9}

hw1 = pd.Series(data = hw1_data)
hw2 = pd.Series(data = hw2_data)

In [ ]:
hw_avg = (hw1 + hw2)/2

hw_avg

**Notice:** The same task would a lot more work with Numpy arrays.

**However** this brings up an interesting point. Oftentimes our data will be incomplete. Pandas deals with incomplete data by labelling it with *NaN* standing for *Not a Number*. Dealing with missing data is one of the most important topics in data science (falling into the larger category of data sanitization). We will discuss how Pandas can help us deal with *NaN* values shortly.

### DataFrames

A **DataFrame** is a two-dimensional labeled data structure that consists of columns and rows. A DataFrame represents a spreadsheet-like data structure where each column is a **Series**.

In [ ]:
data = {
    "Name" : ["John", "Nathan", "Lily", "Corrin"],
    "Age" : [26,27,19,26],
    "City" : ["Hamilton", "Dundas", "Halifax", "Charlottetown"]
}

df = pd.DataFrame(data)

df

In [ ]:
data = [
    ["John", 26, "Hamilton"],
    ['Nathan', 27, "Dundas"],
    ["Lily", 19, "Halifax"],
    ["Corrin", 26, "Charlottetown"]
]

unique_id = [400130523, 400127887, 40130877, 555555555]

cols = ["Name", "Age", "City"]

df = pd.DataFrame(data, columns = cols, index = unique_id)

df

In [ ]:
df["Name"]

In [ ]:
df["City"]

What if we want to see a row instead of a column?

Here we can use the `loc` method!

In [ ]:
df.loc[400130523]

In [ ]:
df.loc[[400130523,555555555]]

### Reading in from file

In [ ]:
df = pd.read_csv('grades.csv')

In [ ]:
df

In [ ]:
df.columns

In [ ]:
df.loc[len(df)+1] = ["Mike", "Wazowski", 400130523, 29.9, 29.9, 29.9, 29.9, 22.2, 22.2, 30.2]

In [ ]:
df.describe()

In [ ]:
df[df[' Final exam mark']> 92.0]

In [ ]:
df.loc[0:5, " Quizzes average":]

### Example dataset

In [ ]:
df = pd.read_csv("JohnBookData.csv")
df= df.loc[:, 'Title': 'Date Added']
df = df.drop(columns = ['Additional Authors', 'Author l-f', 'Binding', 'ISBN', 'ISBN13'])

In [ ]:
pubdate = df['Original Publication Year']
pages = df['Number of Pages']

In [ ]:
fig, ax = plt.subplots(1,2)

fig.tight_layout
p1 = ax[0].hist(pubdate, color = 'red')
ax[0].set_title('Books by Publication Year')
ax[0].set_xlabel('Year')
ax[0].set_ylabel('Count')
p2 = ax[1].hist(pages)
ax[1].set_title('Books by number of pages')
ax[1].set_xlabel('Number of Pages')
ax[1].set_ylabel('Count')
plt.show()

### Example calculation involving grades

In [ ]:
df = pd.read_csv('grades.csv')

### Final grading scheme
1. Scheme 1
- 10% Quizzes
- 20% HW
- 40% Exams (20% each)
- 30% Final Exam
2. Scheme 2
- 10% Quizzes
- 20% HW
- 20% Exams (Best 1 of 2)
- 50% Final Exam

In [ ]:
final_grade1 = 0.1*df[' Quizzes average'] + 0.2*((df[' HW1 mark']+ df[' HW2 mark']+ df[' HW3 mark'])/3) + 0.2*(df[' Exam1 mark']) + 0.2*(df[' Exam2 mark'])+0.3*(df[' Final exam mark'])

final_grade2 = 0.1*df[' Quizzes average'] + 0.2*((df[' HW1 mark']+ df[' HW2 mark']+ df[' HW3 mark'])/3) + 0.2*(df[[' Exam1 mark', ' Exam2 mark']].max(axis = 1))+0.5*(df[' Final exam mark'])

df.insert(10,'Final grade scheme 1', final_grade1)
df.insert(11, 'Final grade scheme 2', final_grade2)

In [ ]:
final_grade = df[['Final grade scheme 1', 'Final grade scheme 2']].max(axis = 1)
df.insert(12, 'Final grade', final_grade)

In [ ]:
df

### Dealing with missing data

Let's now try to accomplish the same goal as before, but this time with a more realistic data set.

In [10]:
gradeBook = pd.read_csv('grades_missing.csv', na_values = [' '])

In [11]:
gradeBook

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark
0,BARRY,LAMB,620565656,96.0,77.0,NaN,91.0,NaN,NaN,91
1,NARIMAN,PELUCHONDELAGARZA,107856531,94.0,76.0,87.0,90.0,90.0,67.0,88
2,VITALY,KHAN,7943944,92.0,79.0,85.0,92.0,76.0,60.0,87
3,NATALYA,SUTRADHAR,114037001,90.0,75.0,78.0,88.0,90.0,67.0,84
4,MAGARET,HIRJI,581943811,88.0,76.0,91.0,98.0,96.0,56.0,81
...,...,...,...,...,...,...,...,...,...,...
246,JANAYA,ELZOEIBY,248015969,94.0,72.0,82.0,91.0,92.0,69.0,93
247,PATRYK,BERNIQUER,970187185,95.0,72.0,88.0,94.0,88.0,67.0,95
248,ARIANNA,DMITROVICH,300391145,91.0,73.0,84.0,94.0,96.0,75.0,83
249,CHERISE,MILEUSNIC,149614639,92.0,78.0,79.0,91.0,90.0,65.0,90
250,DUMITRU,SHAH,849296811,94.0,65.0,86.0,87.0,NaN,NaN,85

We must choose how we deal with NaN values. In the case of grades, inserting zero works, but in other data sets this will not make sense. For instance, in some cases, inserting the mean of the data set is best.

In [12]:
gradeBook = gradeBook.fillna(0)

In [13]:
final_grade1 = 0.1*gradeBook[' Quizzes average'] + 0.2*((gradeBook[' HW1 mark']+ gradeBook[' HW2 mark']+ gradeBook[' HW3 mark'])/3) + 0.2*(gradeBook[' Exam1 mark']) + 0.2*(gradeBook[' Exam2 mark'])+0.3*(gradeBook[' Final exam mark'])

final_grade2 = 0.1*gradeBook[' Quizzes average'] + 0.2*((gradeBook[' HW1 mark']+ gradeBook[' HW2 mark']+ gradeBook[' HW3 mark'])/3) + 0.2*(gradeBook[[' Exam1 mark', ' Exam2 mark']].max(axis = 1))+0.5*(gradeBook[' Final exam mark'])

gradeBook.insert(10,'Final grade scheme 1', final_grade1)
gradeBook.insert(11, 'Final grade scheme 2', final_grade2)

In [14]:
final_grade = gradeBook[['Final grade scheme 1', 'Final grade scheme 2']].max(axis = 1)
gradeBook.insert(12, 'Final grade', final_grade)

In [15]:
gradeBook

,# First name,Last name,Student number,Quizzes average,HW1 mark,HW2 mark,HW3 mark,Exam1 mark,Exam2 mark,Final exam mark,Final grade scheme 1,Final grade scheme 2,Final grade
0,BARRY,LAMB,620565656,96.0,77.0,0.0,91.0,0.0,0.0,91,48.100000,66.300000,66.300000
1,NARIMAN,PELUCHONDELAGARZA,107856531,94.0,76.0,87.0,90.0,90.0,67.0,88,84.066667,88.266667,88.266667
2,VITALY,KHAN,7943944,92.0,79.0,85.0,92.0,76.0,60.0,87,79.566667,84.966667,84.966667
3,NATALYA,SUTRADHAR,114037001,90.0,75.0,78.0,88.0,90.0,67.0,84,81.666667,85.066667,85.066667
4,MAGARET,HIRJI,581943811,88.0,76.0,91.0,98.0,96.0,56.0,81,81.166667,86.166667,86.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,JANAYA,ELZOEIBY,248015969,94.0,72.0,82.0,91.0,92.0,69.0,93,85.833333,90.633333,90.633333
247,PATRYK,BERNIQUER,970187185,95.0,72.0,88.0,94.0,88.0,67.0,95,85.933333,91.533333,91.533333
248,ARIANNA,DMITROVICH,300391145,91.0,73.0,84.0,94.0,96.0,75.0,83,84.933333,86.533333,86.533333
249,CHERISE,MILEUSNIC,149614639,92.0,78.0,79.0,91.0,90.0,65.0,90,83.733333,88.733333,88.733333
250,DUMITRU,SHAH,849296811,94.0,65.0,86.0,87.0,0.0,0.0,85,50.766667,67.766667,67.766667

Depending on the kind of data, sometimes it is best to remove all data that contains *NaN* values. For instance, when getting ethics approval for a research project involving a survey, it is sometimes required that all partially completed surveys be removed from the data set.

We can use the `dropna()` command for this.